#ifndef CFG_H
#define CFG_H

//#define CHECK_SIZES

#define MAX_CPLX_STACK_SIZE 30
#define MAX_ARRAY_STACK_SIZE 30
#define MAX_STAT_ARRAY_STACK_SIZE 30
#define MAX_UNDEF_STACK_SIZE 30
#define MAX_POINTER_STACK_SIZE 30

//#define USE_STATIC_ARRAY

#define MEMBANK_MAX_SIZE 4096

#define FIFO_BUFF_MAX_SIZE 7 //(2^x)-1

//#define STATIC_ALLOC

#define MAX_TYPES_PER_CTLG 5
#define USER_BASE_TYPE_ID  30

#endif //CFG_H